var annotated_dup =
[
    [ "AIAssistant", "class_a_i_assistant.html", "class_a_i_assistant" ],
    [ "AIObjectGenerator", "class_a_i_object_generator.html", "class_a_i_object_generator" ],
    [ "AIScript", "class_a_i_script.html", "class_a_i_script" ],
    [ "AISettings", "class_a_i_settings.html", "class_a_i_settings" ],
    [ "AISettingsFileManager", "class_a_i_settings_file_manager.html", "class_a_i_settings_file_manager" ],
    [ "AISettingsSerializable", "class_a_i_settings_serializable.html", "class_a_i_settings_serializable" ],
    [ "ColorArrayObject", "class_color_array_object.html", "class_color_array_object" ],
    [ "ColorExtruder", "class_color_extruder.html", "class_color_extruder" ],
    [ "ColorScriptDemo", "class_color_script_demo.html", "class_color_script_demo" ],
    [ "ExtensionTabs", "class_extension_tabs.html", "class_extension_tabs" ],
    [ "FileManager", "class_file_manager.html", "class_file_manager" ],
    [ "GptCompletionRequest", "class_gpt_completion_request.html", "class_gpt_completion_request" ],
    [ "GptCompletionResponse", "struct_gpt_completion_response.html", "struct_gpt_completion_response" ],
    [ "GptRequest", "class_gpt_request.html", "class_gpt_request" ],
    [ "GptResponse", "class_gpt_response.html", "class_gpt_response" ],
    [ "HelpBox", "class_help_box.html", "class_help_box" ],
    [ "MessageListBuilder", "class_message_list_builder.html", "class_message_list_builder" ],
    [ "OpenAiApiManager", "class_open_ai_api_manager.html", "class_open_ai_api_manager" ],
    [ "OpenAiInputBuilder", "class_open_ai_input_builder.html", "class_open_ai_input_builder" ],
    [ "OpenAiStandardPrompts", "class_open_ai_standard_prompts.html", "class_open_ai_standard_prompts" ],
    [ "PromptManager", "class_prompt_manager.html", "class_prompt_manager" ],
    [ "ReflectiveMethods", "class_reflective_methods.html", "class_reflective_methods" ],
    [ "RequestMessage", "class_request_message.html", "class_request_message" ],
    [ "ScriptUtil", "class_script_util.html", "class_script_util" ],
    [ "SingleExtensionApplication", "class_single_extension_application.html", "class_single_extension_application" ],
    [ "TestScript", "class_test_script.html", "class_test_script" ]
];